---
title: "Visualization with ggplot2 (1)"
author: "Zoey Zhao"
date: "10/5/2021"
output: github_document
---
```{r message=FALSE}
library(tidyverse)
library(ggridges)
```
```{r message=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
## Scatterplot

tmax vs tmin

```{r, warning=FALSE}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point()
```
you can save ggplots

```{r warning=FALSE}
ggp_tmax_tmin <-
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

ggp_tmax_tmin
```
## Let's fancy it up

Ass ... color? lines? other studd?

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5)+
  geom_smooth(se =FALSE)
```

```{r warning=FALSE}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

## Use data manipulation as part of this
```{r message=FALSE}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)
```

## Stacking geoms
Which geoms do you want?

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name))+
  geom_smooth()
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```
## Univariate plots

```{r warning=FALSE, message=FALSE}
ggplot(weather_df, aes(x = tmax)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")

#Violin plots
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")

#Ridge plots
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```


